2024-07-26 02:27:11,264 - INFO - Searching for TF2 install directory
2024-07-26 02:27:17,906 - INFO - TF2 install directory found: D:\Game Libraries\Steam Library\steamapps\common\Team Fortress 2\tf\cfg
2024-07-26 02:27:23,377 - INFO - Destination folder: D:\Game Libraries\Steam Library\steamapps\common\Team Fortress 2\tf\cfg\overrides
2024-07-26 02:27:23,377 - INFO - Downloading latest release from https://github.com/7eventy7/TF2-MASTERCLASS-CONFIG/releases/latest/download/TF2-MASTERCLASS-CONFIG.zip
2024-07-26 02:27:23,929 - ERROR - Error downloading release: HTTP Error 404: Not Found
2024-07-26 02:27:23,929 - ERROR - An error occurred: HTTP Error 404: Not Found
2024-07-26 02:27:23,931 - ERROR - Traceback (most recent call last):
  File "C:\Users\Garnet\Documents\GitHub\TF2-MASTERCLASS-CONFIG\install-tf2-masterclass-config.py", line 130, in main
    zip_file = download_latest_release(LATEST_RELEASE_URL)
  File "C:\Users\Garnet\Documents\GitHub\TF2-MASTERCLASS-CONFIG\install-tf2-masterclass-config.py", line 62, in download_latest_release
    response = urlopen(url)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Garnet\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

